\doxysection{cudf\+::logic\+\_\+error结构体 参考}
\hypertarget{structcudf_1_1logic__error}{}\label{structcudf_1_1logic__error}\index{cudf::logic\_error@{cudf::logic\_error}}


Exception thrown when logical precondition is violated.  




{\ttfamily \#include $<$error.\+hpp$>$}



类 cudf\+::logic\+\_\+error 继承关系图\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=159pt]{structcudf_1_1logic__error__inherit__graph}
\end{center}
\end{figure}


cudf\+::logic\+\_\+error 的协作图\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=159pt]{structcudf_1_1logic__error__coll__graph}
\end{center}
\end{figure}
\doxysubsubsection*{Public 成员函数}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{structcudf_1_1logic__error_a20ce9586edc55454a01889e91c8c7023}{logic\+\_\+error}} (char const \texorpdfstring{$\ast$}{*}const message)
\begin{DoxyCompactList}\small\item\em Constructs a \doxylink{structcudf_1_1logic__error}{logic\+\_\+error} with the error message. \end{DoxyCompactList}\item 
\mbox{\hyperlink{structcudf_1_1logic__error_a6901fb3ad36a2dff34d1b68406553b53}{logic\+\_\+error}} (std\+::string const \&message)
\begin{DoxyCompactList}\small\item\em Construct a new logic error object with error message \end{DoxyCompactList}\end{DoxyCompactItemize}


\doxysubsection{详细描述}
Exception thrown when logical precondition is violated. 

This exception should not be thrown directly and is instead thrown by the CUDF\+\_\+\+EXPECTS macro. 

在文件 \mbox{\hyperlink{error_8hpp_source}{error.\+hpp}} 第 \mbox{\hyperlink{error_8hpp_source_l00037}{37}} 行定义.



\doxysubsection{构造及析构函数说明}
\Hypertarget{structcudf_1_1logic__error_a20ce9586edc55454a01889e91c8c7023}\label{structcudf_1_1logic__error_a20ce9586edc55454a01889e91c8c7023} 
\index{cudf::logic\_error@{cudf::logic\_error}!logic\_error@{logic\_error}}
\index{logic\_error@{logic\_error}!cudf::logic\_error@{cudf::logic\_error}}
\doxysubsubsection{\texorpdfstring{logic\_error()}{logic\_error()}\hspace{0.1cm}{\footnotesize\ttfamily [1/2]}}
{\footnotesize\ttfamily cudf\+::logic\+\_\+error\+::logic\+\_\+error (\begin{DoxyParamCaption}\item[{char const \texorpdfstring{$\ast$}{*}const}]{message }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



Constructs a \doxylink{structcudf_1_1logic__error}{logic\+\_\+error} with the error message. 


\begin{DoxyParams}{参数}
{\em message} & Message to be associated with the exception \\
\hline
\end{DoxyParams}


在文件 \mbox{\hyperlink{error_8hpp_source}{error.\+hpp}} 第 \mbox{\hyperlink{error_8hpp_source_l00043}{43}} 行定义.

\Hypertarget{structcudf_1_1logic__error_a6901fb3ad36a2dff34d1b68406553b53}\label{structcudf_1_1logic__error_a6901fb3ad36a2dff34d1b68406553b53} 
\index{cudf::logic\_error@{cudf::logic\_error}!logic\_error@{logic\_error}}
\index{logic\_error@{logic\_error}!cudf::logic\_error@{cudf::logic\_error}}
\doxysubsubsection{\texorpdfstring{logic\_error()}{logic\_error()}\hspace{0.1cm}{\footnotesize\ttfamily [2/2]}}
{\footnotesize\ttfamily cudf\+::logic\+\_\+error\+::logic\+\_\+error (\begin{DoxyParamCaption}\item[{std\+::string const \&}]{message }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



Construct a new logic error object with error message 


\begin{DoxyParams}{参数}
{\em message} & Message to be associated with the exception \\
\hline
\end{DoxyParams}


在文件 \mbox{\hyperlink{error_8hpp_source}{error.\+hpp}} 第 \mbox{\hyperlink{error_8hpp_source_l00050}{50}} 行定义.



该结构体的文档由以下文件生成\+:\begin{DoxyCompactItemize}
\item 
D\+:/git\+Library/cudf/cpp/include/cudf/utilities/\mbox{\hyperlink{error_8hpp}{error.\+hpp}}\end{DoxyCompactItemize}
